### Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python



### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

## Multidimensional array

In [6]:
my_list1 = [1,2,3,4,5,6]
my_list2 = [7,6,3,5,1,8]
my_list3 = [1,2,5,4,5,2]
arr1 = np.array([my_list1,my_list2,my_list3])
print(arr1)

[[1 2 3 4 5 6]
 [7 6 3 5 1 8]
 [1 2 5 4 5 2]]


In [7]:
arr1

array([[1, 2, 3, 4, 5, 6],
       [7, 6, 3, 5, 1, 8],
       [1, 2, 5, 4, 5, 2]])

In [8]:
type(arr1)

numpy.ndarray

### Indexing

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr[3]

4

In [11]:
arr1

array([[1, 2, 3, 4, 5, 6],
       [7, 6, 3, 5, 1, 8],
       [1, 2, 5, 4, 5, 2]])

In [12]:
arr1[1:2] ## first row second column

array([[7, 6, 3, 5, 1, 8]])

In [13]:
arr1[1:,:2] ## print all from row first 

array([[7, 6],
       [1, 2]])

In [14]:
arr1[:,3:] ## start 3rd index

array([[4, 5, 6],
       [5, 1, 8],
       [4, 5, 2]])

In [15]:
arr1[:,:3] ## start first to third

array([[1, 2, 3],
       [7, 6, 3],
       [1, 2, 5]])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr[3:]=100

In [18]:
arr

array([  1,   2,   3, 100, 100])

In [19]:
## create array and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [21]:
np.ones((2,5),dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# random distribution
np.random.rand(3,3)


array([[0.66574135, 0.39401564, 0.65716446],
       [0.15713278, 0.40465058, 0.38287697],
       [0.88465258, 0.58848577, 0.54903538]])

In [23]:
arr_ex=np.random.randn(4,4)


In [24]:
arr_ex

array([[ 0.48170697,  0.06852298, -0.81836812, -0.71299382],
       [ 0.56509925,  0.01497589,  0.34884982,  0.33285903],
       [ 0.3588202 ,  0.01601136, -0.58775674,  0.16681067],
       [ 0.84264229,  0.92021284, -1.91948603, -2.53954832]])

### numpy.linspace

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
It is similar to the arrange function. However, it doesn?t allow us to specify the step size in the syntax.

In [25]:
np.linspace(2.0, 3.0, num=5)



array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [26]:
np.linspace(2.0, 3.0, num=5, endpoint=False)


array([2. , 2.2, 2.4, 2.6, 2.8])

In [27]:

np.linspace(2.0, 3.0, num=5, retstep=True)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [28]:
import numpy as np
import pandas as pd

In [29]:
myarray = np.array([[1,2,3,4,5]],np.int8)

In [30]:
myarray

array([[1, 2, 3, 4, 5]], dtype=int8)

In [31]:
myarray[0,1]

2

In [32]:
myarray.shape

(1, 5)

In [33]:
myarray.dtype

dtype('int8')

In [34]:
myarray[0,1] = 55

In [35]:
myarray

array([[ 1, 55,  3,  4,  5]], dtype=int8)

## Array creation: Conversion from other Python structures

In [36]:
listarray = np.array([[1,2,3,4],[4,5,6,7],[2,4,5,7]])

In [37]:
listarray

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 4, 5, 7]])

In [38]:
listarray.shape

(3, 4)

In [39]:
listarray.dtype

dtype('int32')

In [40]:
listarray.size

12

In [41]:
zeros = np.zeros((2,5))

In [42]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:

arr= np.arange(15)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
lspace = np.linspace(1,5,12)

In [46]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [47]:
lspace = np.linspace(1,5,5)

In [48]:
lspace

array([1., 2., 3., 4., 5.])

In [49]:
emp = np.empty((4,5)) ## gives a rando value

In [50]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.11260755e-306,
        1.60219578e-306, 1.29062229e-306],
       [1.78010255e-306, 1.86920736e-306, 1.11256817e-306,
        1.06811422e-306, 1.42417221e-306],
       [1.11260619e-306, 8.90094053e-307, 1.86919378e-306,
        1.06809792e-306, 1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307, 7.56599806e-307]])

In [51]:
emp_like = np.empty_like(lspace)

In [52]:
emp_like

array([1., 2., 3., 4., 5.])

In [53]:
ide = np.identity((45))

In [54]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [55]:
ide.shape

(45, 45)

In [56]:
arr = np.arange(99)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [58]:
arr = arr.reshape(3,33)

In [59]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [60]:
arr = arr.ravel()

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr.shape

(99,)

In [63]:
x= [[1,2,3],[4,5,6],[7,8,9]]

In [64]:
arr = np.array(x)

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr.sum(axis = 0)

array([12, 15, 18])

In [67]:
arr.sum(axis = 1)

array([ 6, 15, 24])

In [69]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [70]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [71]:
arr.ndim

2

In [72]:
arr.size

9

In [74]:
arr.nbytes

36

In [75]:
one = np.array([[1,3,55,67,3]])

In [76]:
one.argmax()

3

In [77]:
one.argmin()

0

In [78]:
one.argsort()

array([[0, 1, 4, 2, 3]], dtype=int64)

In [79]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr.argmax()

8

In [81]:
arr.argmin()

0

In [82]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [83]:
a = np.arange(15).reshape(3, 5)

In [84]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
a.shape

(3, 5)

In [87]:
c = np.arange(24).reshape(2,3,4)         # 3d array

In [88]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
 print(np.arange(10000).reshape(100,100))


[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
