In [1]:
import numpy as np

In [2]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,4]])
print(my_array)

[[1 2 3 4 5]
 [6 7 8 9 4]]


In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a =np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [5]:
a =np.array([1,2,3],dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [6]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


### resizes the ndarray

In [10]:
a= np.array([[1,2,3],[4,5,6]])
a.shape =(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
a= np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)   # use reshape function to resize the array
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
a = np.arange(24)
print(a)
b=a.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### numpy.flags

In [14]:
x =np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


### np.zeros

In [15]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [17]:
x = np.zeros((5),dtype = np.int)
print(x)

[0 0 0 0 0]


In [18]:
x=np.zeros((2,2),dtype = [('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## np.ones()


In [19]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [20]:
x = np.ones([2,2],dtype = int)
print(x)

[[1 1]
 [1 1]]


In [22]:
import numpy as np 
# dtype set 
x = np.arange(5, dtype = float)
print (x)

[0. 1. 2. 3. 4.]


In [23]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print (x)

[10 12 14 16 18]


## Indexing & Slicing

In [24]:
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [25]:
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [26]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print (b)

5


In [27]:

# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [28]:

# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [31]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a) 

# slice items starting from index
print ('Now we will slice the array from the index a[1:]')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [34]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


## Broadcasting

In [36]:

import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [37]:

import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a )
print ('\n')  
   
print ('Second array:') 
print (b )
print ('\n')  
   
print ('First Array + Second Array' )
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
